export const quotes = [
  { text: 'When the time is right, I, the Lord, will make it happen.', ref: 'Isaiah 60:22' },
  { text: 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.', ref: 'Jeremiah 29:11' },
  { text: 'The Lord is my shepherd; I shall not want.', ref: 'Psalm 23:1' },
  { text: 'Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.', ref: 'Joshua 1:9' },
  { text: 'Trust in the Lord with all your heart and lean not on your own understanding.', ref: 'Proverbs 3:5' },
  { text: 'I can do all things through Christ who strengthens me.', ref: 'Philippians 4:13' },
  { text: 'The Lord is my light and my salvation — whom shall I fear?', ref: 'Psalm 27:1' },
  { text: 'Cast all your anxiety on him because he cares for you.', ref: '1 Peter 5:7' },
  { text: 'And we know that in all things God works for the good of those who love him.', ref: 'Romans 8:28' },
  { text: 'Be still, and know that I am God.', ref: 'Psalm 46:10' },
  { text: 'The Lord will fight for you; you need only to be still.', ref: 'Exodus 14:14' },
  { text: 'God is our refuge and strength, an ever-present help in trouble.', ref: 'Psalm 46:1' },
  { text: 'Come to me, all you who are weary and burdened, and I will give you rest.', ref: 'Matthew 11:28' },
  { text: 'The peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.', ref: 'Philippians 4:7' },
  { text: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.', ref: 'Philippians 4:6' },
  { text: 'But those who hope in the Lord will renew their strength. They will soar on wings like eagles.', ref: 'Isaiah 40:31' },
  { text: 'He heals the brokenhearted and binds up their wounds.', ref: 'Psalm 147:3' },
  { text: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.', ref: 'Psalm 34:18' },
  { text: 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.', ref: 'John 3:16' },
  { text: 'In this world you will have trouble. But take heart! I have overcome the world.', ref: 'John 16:33' },
  { text: 'The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you.', ref: 'Numbers 6:24\u201325' },
  { text: 'Delight yourself in the Lord, and he will give you the desires of your heart.', ref: 'Psalm 37:4' },
  { text: 'The name of the Lord is a fortified tower; the righteous run to it and are safe.', ref: 'Proverbs 18:10' },
  { text: 'He gives strength to the weary and increases the power of the weak.', ref: 'Isaiah 40:29' },
  { text: 'Your word is a lamp for my feet, a light on my path.', ref: 'Psalm 119:105' },
  { text: 'The Lord is gracious and compassionate, slow to anger and rich in love.', ref: 'Psalm 145:8' },
  { text: 'For where two or three gather in my name, there am I with them.', ref: 'Matthew 18:20' },
  { text: 'With God all things are possible.', ref: 'Matthew 19:26' },
  { text: 'May the God of hope fill you with all joy and peace as you trust in him.', ref: 'Romans 15:13' },
  { text: 'Create in me a pure heart, O God, and renew a steadfast spirit within me.', ref: 'Psalm 51:10' },
  { text: 'The joy of the Lord is your strength.', ref: 'Nehemiah 8:10' },
  { text: 'Wait for the Lord; be strong and take heart and wait for the Lord.', ref: 'Psalm 27:14' },
  { text: 'This is the day the Lord has made; let us rejoice and be glad in it.', ref: 'Psalm 118:24' },
  { text: 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.', ref: '1 Corinthians 13:4' },
  { text: 'Faith is confidence in what we hope for and assurance about what we do not see.', ref: 'Hebrews 11:1' },
  { text: 'Blessed are the pure in heart, for they will see God.', ref: 'Matthew 5:8' },
  { text: 'The Lord is my rock, my fortress and my deliverer.', ref: 'Psalm 18:2' },
  { text: 'Do not fear, for I am with you; do not be dismayed, for I am your God.', ref: 'Isaiah 41:10' },
  { text: 'Let the morning bring me word of your unfailing love, for I have put my trust in you.', ref: 'Psalm 143:8' },
  { text: 'If God is for us, who can be against us?', ref: 'Romans 8:31' },
  { text: 'You are the light of the world. A town built on a hill cannot be hidden.', ref: 'Matthew 5:14' },
  { text: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives.', ref: 'John 14:27' },
  { text: 'The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you.', ref: 'Zephaniah 3:17' },
  { text: 'In all your ways submit to him, and he will make your paths straight.', ref: 'Proverbs 3:6' },
  { text: 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights.', ref: 'James 1:17' },
  { text: 'Commit to the Lord whatever you do, and he will establish your plans.', ref: 'Proverbs 16:3' },
  { text: 'As for me and my household, we will serve the Lord.', ref: 'Joshua 24:15' },
  { text: 'The steadfast love of the Lord never ceases; his mercies never come to an end. They are new every morning.', ref: 'Lamentations 3:22\u201323' },
  { text: 'Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.', ref: 'Ephesians 4:32' },
  { text: 'For we walk by faith, not by sight.', ref: '2 Corinthians 5:7' },
];
